### ISSUE TITLE
Error on filter with Dynagrid and Pjax

### ISSUE THREAD

**Issue by KirillRyzhkov** [kartik-v/yii2-dynagrid#101]
Select2 cannot reinitialize after filtering when using DynaGrid with pjax=true
<pre>
kv-dynagrid.js:127 Uncaught ReferenceError: initSelect2Loading is not defined
</pre>

**Comment by KirillRyzhkov** [comment]
The issue "minimum-stability": "stable" installs  @version   1.4.2 but need version  @version   1.4.5. Can you fix this?

**Comment by kartik-v** [comment]
It needs to be fixed at your end... the latest stable release is v1.4.4

Version 1.4.5 will be tagged soon...
