### ISSUE TITLE
Table headers are not moving with the rest of the table

### ISSUE THREAD

**Issue by AntoninSlejska** [kartik-v/yii2-dynagrid#102]
I use Dynagrid for relative big tables. When the table is wider as the browser window, and I move with the rider, then the values move, but the header not. You can try it on the demo page: http://demos.krajee.com/dynagrid-demo
See:
![Dynagrid - Headers](https://dl.dropboxusercontent.com/u/4391854/dynagrid-table-headers.png)

**Comment by kartik-v** [comment]
It depends on the external plugin configuration (float table header).

- If you do not need sticky headers disable floatHeader 

- or set the plugin options for floatHeader plugin as [described here in the docs](http://demos.krajee.com/grid#floating-header) - e.g. the floatOverflowContainer etc.

**Comment by AntoninSlejska** [comment]
Thank you for the suggestions.

 - I need the floatHeader, because the users need to work with long lists of data.
 - When I use: *'floatOverflowContainer' => true,* then the list is only 300px heigh. The problem lies in CSS: *kv-grid-wrapper { height: 300px; ...*

It is possible to manipulate the height with JavaScript, e.g.: *$(".kv-grid-wrapper").height($(".kv-grid-table").height());*
But I'm not sure, if it is the best solution.

**Comment by alexlobuono** [comment]
I have adopted this hack:
CSS:
.kv-grid-wrapper {
    height: auto;
}
JS:
$('.kv-grid-wrapper').each(function() {
        $(this).css('height', $(this).height()-1);
});

Thanks for all Kartik
