### ISSUE TITLE
Some possible html issues

### ISSUE THREAD

**Issue by sercon** [kartik-v/yii2-dynagrid#104]
line 325 column 143 - Error: Duplicate ID “dynagridsettings-name”.
line 297 column 143 - Info: The first occurrence of ID “dynagridsettings-name” was here.
line 330 column 182 - Error: Duplicate ID “dynagridsettings-editid”.
line 302 column 182 - Info: The first occurrence of ID “dynagridsettings-editid” was here.
line 336 column 170 - Error: Duplicate ID “dynagridsettings-category”.
line 308 column 174 - Info: The first occurrence of ID “dynagridsettings-category” was here.
line 336 column 265 - Error: Duplicate ID “dynagridsettings-storage”.
line 308 column 269 - Info: The first occurrence of ID “dynagridsettings-storage” was here.
line 336 column 369 - Error: Duplicate ID “dynagridsettings-userspecific”.
line 308 column 373 - Info: The first occurrence of ID “dynagridsettings-userspecific” was here.
line 336 column 475 - Error: Duplicate ID “dynagridsettings-dynagridid”.
line 308 column 479 - Info: The first occurrence of ID “dynagridsettings-dynagridid” was here.
line 453 column 126 - Error: End tag “form” seen, but there were open elements.
line 351 column 137 - Error: Unclosed element “div”. (<div class="dynagrid-config-form">)

**Comment by kartik-v** [comment]
You seem to have multiple dynagrid instances on the same page. This will need an enhancement. Till this fix is done, you may need to use only one Dynagrid per page.
