### ISSUE TITLE
Class 'kartik\widgets\DateTimePicker' not found

### ISSUE THREAD

**Issue by rienheuver** [kartik-v/yii2-dynagrid#107]
I followed the instructions exactly as I should have: installed through composer and added the `user kartik\widgets\DateTimePicker` to my view. Still I get this error: `Class 'kartik\widgets\DateTimePicker' not found`. Already tried removing vendor/ and doing a new `composer install --prefer-dist` and a `composer update`.

**Comment by rienheuver** [comment]
Apparently the documentation is wrong here. The correct usage is:
`use kartik\datetime\DateTimePicker` instead of `use kartik\widgets\DateTimePicker`

**Comment by kartik-v** [comment]
It depends on if you are installing `yii2-widgets` (as the package) or `yii2-widget-datetimepicker` (in isolation)... these widgets were earlier part of `yii2-widgets` and the docs was made then... but if you only install yii2-widget-datetimepicker --- then you need to use `kartik\datetime\DateTimePicker`.

**Comment by rienheuver** [comment]
Perhaps you want to state that more clearly on [this page](http://demos.krajee.com/widget-details/datetimepicker#usage).
