### ISSUE TITLE
defaultOrder

### ISSUE THREAD

**Issue by BenasPaulikas** [kartik-v/yii2-dynagrid#111]
If no sorting was creating nor selected

```
    $dataProvider = new ActiveDataProvider([
        'query' => $query,
        'pagination' => [
            'pageSize' => false,
        ],
        'sort' => ['defaultOrder' => 'id DESC']
    ]);
```

defaultOrder is not working

**Comment by metola** [comment]
See the [documentatión and examples](http://www.yiiframework.com/doc-2.0/yii-data-activedataprovider.html)
`'sort'=> ['defaultOrder' => ['id'=>SORT_DESC]]`
