### ISSUE TITLE
TypeError: $(...).yiiGridView is not a function

### ISSUE THREAD

**Issue by somnathmuluk** [kartik-v/yii2-dynagrid#113]
Getting error when called **yiiGridView**. 

Also when selecting check box for all row selection. Nothing happens. 

I think Javascript is not loaded. I do not understand why Javascript is not loaded in a page.

How to debug this problem?

**Comment by kartik-v** [comment]
You need to debug for javascript errors on your browser console and it may be related to your app. Closing this as this is not related to the extension.
