### ISSUE TITLE
Problem with multiple Select2 when i save filters

### ISSUE THREAD

**Issue by stepancher** [kartik-v/yii2-dynagrid#132]
Hello Kartik!
Use your dynagrid and Select2 for multiple filtering table like this

```
    [
        'label' => 'Article',
        'attribute' => 'article_id',
        'value' => function ($model) {
            return $model->article ? $model->article->name : '';
        },
        'filterType' => GridView::FILTER_SELECT2,
        'filter' => [1 => 'Article 1', 2=> 'Article 2'],
        'filterWidgetOptions' => [
            'pluginOptions' => ['allowClear' => true, 'multiple' => true],
        ],
    ],
```

When i try to save my filter in dynagrid, it give me exception:

Array to string conversion  
in line 159 kartik\dynagrid\models\DynaGridSettings 

`$out .= "<li>{$label} = {$value}</li>";`

**Comment by metola** [comment]
Hi, stepancher, upload last versión and try it, I had the same issue, but now work well.
