### ISSUE TITLE
Disabling the css loader in kartik dynagrid reload

### ISSUE THREAD

**Issue by geoffreymwangian** [kartik-v/yii2-dynagrid#135]
I would like to disable the css loader since am performing the grid reload every 5 seconds but i havent found a way yet
<?php
  $script = <<< JS
function reloadgrid() {
var intervalID = setInterval(function() {
   $.pjax.reload({container:'#trackyard-pjax'});
}, 3000);
setTimeout(function() {
    clearInterval(intervalID);
}, 18000);
};

reloadgrid();
JS;
$this->registerJS($script, \yii\web\VIEW::POS_HEAD);
?>

How do i disable the css loader

**Comment by kartik-v** [comment]
Override it in `GridView::pjaxSettings['loadingCssClass']`.

```php
echo Dynagrid::widget([
    'gridOptions' => [
        'pjaxSettings' => [
            'loadingCssClass' => 'your-custom-class', // override your css class here
        ]
    ]
]);
```
