### ISSUE TITLE
Having table outside of "db" database

### ISSUE THREAD

**Issue by mikface** [kartik-v/yii2-dynagrid#137]
In DynaGridStore.php there is forced to get data from "db" instead of option to choose, which db form your config you want to choose.
If somebody has more databases connected to yii and he wants to create table with dynagrid settings in another one than "db", he wont reach these settings.

**Comment by metola** [comment]
Yes, If you have more than one "db", and need connect it all, you have to have another "db" ,whose rol is the principal, and each model chosse other "db":
` public static function getDb()
    {
        $Db='db_cool'; 
        return Yii::$app->get($Db); 
    }`
if you want separate tables , you need create app (backend,frontend,x-end.....) for each db and change settings db dynagrid.

**Comment by kartik-v** [comment]
Enhanced via #163. You can now configure the `Module::dbSettings['connection']` and/or `Module::dbSettingsDtl['connection']` to control the component name that you will use for your dynagrid database. It defaults to `db`.
