### ISSUE TITLE
"Array to string conversion" when filter is array

### ISSUE THREAD

**Issue by ittaskeu** [kartik-v/yii2-dynagrid#140]
Hello kartik,
I have problem when stored filter is array.

file: vendor/kartik-v/yii2-dynagrid/models/DynaGridSettings.php
error message: Array to string conversion
line: 163 in method getDataConfig

`if ($this->category === DynaGridStore::STORE_FILTER) {
            foreach ($data as $attribute => $value) {
                //problem when $value is array
                $label = isset($attribute['label']) ? $attribute['label'] : Inflector::camel2words($attribute);
                $out .= "<li>{$label} = {$value}</li>";
            }
        }`

**Comment by kartik-v** [comment]
Should be resolved by #126.
