### ISSUE TITLE
Dynagrid's pageSize configuration value not applied when using ArrayDataProvider

### ISSUE THREAD

**Issue by antoniom** [kartik-v/yii2-dynagrid#141]
### The problem:
Suppose that you have the following code:

```php
$query = new yii\db\Query;
$provider = new yii\data\ArrayDataProvider([
    'allModels' => $query->from('Employee')->all(),
    'pagination' => [
        'pageSize' => 10,
    ],
]);

echo \kartik\dynagrid\DynaGrid::widget([
    'columns' => ['EmployeeID', 'UserName'],
    'gridOptions'=>[
        'dataProvider'=>$provider,
        'panel'=>[
            'before'=>'{dynagrid}'
        ],
    ],
    'options' => ['id' => 'dynagrid-demo']
]);
```

As you can see the default `pageSize` set to `ArrayDataProvider` is 10. The GridView rendered is the following:
![screenshot from 2016-11-24 11 39 39](https://cloud.githubusercontent.com/assets/842181/20593502/61b8d17a-b23b-11e6-9f83-cd31cfcdba09.png)

If someone clicks the Grid Configuration options and change the page size from 10 to 5, he would expect the items per page to be reduced at 5. 
![screenshot from 2016-11-24 11 46 41](https://cloud.githubusercontent.com/assets/842181/20593632/d6a9d24a-b23b-11e6-8211-0ea4a0948539.png)

However the rows per page stay the same, i.e. the new configuration value is never applied.

### Possible Solution:
After some research on the `DynaGrid` class I found that `getAttributeLabel()` method is forcing `ArrayDataProvider` to populate its models **before** the new `Pagination` object is applied, i.e.
```php
$models = $provider->getModels();
if (($model = reset($models)) instanceof Model) {
    return $model->getAttributeLabel($attribute);
} else {
   return Inflector::camel2words($attribute);
}
```
A possible fix could be to invalidate the provider's contents by calling [refresh()](https://github.com/yiisoft/yii2/blob/master/framework/data/BaseDataProvider.php#L252), i.e.
```php
$models = $provider->getModels();
$provider->refresh();
if (($model = reset($models)) instanceof Model) {
    return $model->getAttributeLabel($attribute);
} else {
   return Inflector::camel2words($attribute);
}
```
I can provide a PR for the above fix, or you may come up with a more elegant solution.

**Comment by kartik-v** [comment]
Sure please submit a PR... and let know if it works fine on your tests.

**Comment by metola** [comment]
Hi, I have same problem and fix with `$provider->refresh();` in `getAttributeLabel` function from dynagrid.php
