### ISSUE TITLE
Name of action column

### ISSUE THREAD

**Issue by AndersonDan** [kartik-v/yii2-dynagrid#150]
How to set a friendly name for the action column?

![drop down action column](https://cloud.githubusercontent.com/assets/10473169/23336922/7dcaea4a-fbbc-11e6-880f-48c2b8426112.jpg)

**Comment by kartik-v** [comment]
Set the `header` property of the action column to a string you need.

**Comment by githubjeka** [comment]
Same too

`getColumnLabel` is violates the L from SOLID. . I can't get labels from Models,, need to copy to `header` colums. It's very very very bad..

**Comment by kartik-v** [comment]
@githubjeka would appreciate if you can share details of any issue and what your proposal is to overcome that rather than just a critical remark from your end which is of no help..

@AndersonDan will need to look into your proposed suggestion.

**Comment by githubjeka** [comment]
By default Yii2 uses to get attribute labels method from search model.

```php
    protected function getAttributeLabel($attribute)
    {
        $provider = $this->gridOptions['dataProvider'];
        /** @var Model $model */
        if ($provider instanceof ActiveDataProvider && $provider->query instanceof ActiveQueryInterface) {
            /** @var ActiveQuery $query */
            $query = $provider->query;
            $model = new $query->modelClass;
            return $model->getAttributeLabel($attribute);
        }
        $models = $provider->getModels();
        if (($model = reset($models)) instanceof Model) {  // <<<<< THIS BEHAVIOR DEFAULT BY YII2
            return $model->getAttributeLabel($attribute);
        } else {
            return Inflector::camel2words($attribute);
        }
    }
```

your code `$provider instanceof ActiveDataProvider ...` is violates the [L](https://en.wikipedia.org/wiki/Liskov_substitution_principle). Need delete this code :) If you want to have it has saved, you need add flag, that enable this behavior, by default it should be off.

**Comment by githubjeka** [comment]
Oh, sorry for this. I've got it all mixed up, your code correct.

I just thought of something that is not exist... REF https://github.com/yiisoft/yii2/issues/4504
