### ISSUE TITLE
Possible Bug - pagination getPageCount() always return 0

### ISSUE THREAD

**Issue by m26404020** [kartik-v/yii2-dynagrid#152]
This makes the summary to be like this: Showing 1-10 of 0 items.

I'm using SqlDataProvider for my data provider

**Comment by kartik-v** [comment]
Duplicate to #152.

Cannot reproduce this. 

You must configure `totalCount` property of the SqlDataProvider to the total record count value as highlighted in Yii Docs and you should be able to see that in Dynagrid output (as tested by me separately).
