### ISSUE TITLE
Default hidden column

### ISSUE THREAD

**Issue by appmake** [kartik-v/yii2-dynagrid#160]
How to hide several fields by default, so that the user can then display them himself?

**Comment by metola** [comment]
Hi, if you check demo [http://demos.krajee.com/dynagrid-demo](http://demos.krajee.com/dynagrid-demo) , you can see publish_date, that it is a hide column.
The attribute is visible (set to false).
`
            [
            'attribute'=>'Name',
            'visible'=>false,
            ],`
