### ISSUE TITLE
Personalize pagesize delete order and hidden columns

### ISSUE THREAD

**Issue by metola** [kartik-v/yii2-dynagrid#161]
Hi Kartik,
Since recently, I have find a error in personalize.
When I change the pagesize (and press enter) , and I have hidden columns or diferent order in visible columns, it save the pagesize new, but the hidden columns and order visible columns destroy.
In the demo gridview, can view the problem:
![2](https://user-images.githubusercontent.com/8111455/28525599-0c56f974-7085-11e7-8449-972e1f4f03f3.PNG)
![3](https://user-images.githubusercontent.com/8111455/28525619-18cb0aba-7085-11e7-8832-995817c70010.PNG)
![4](https://user-images.githubusercontent.com/8111455/28525627-1d139ccc-7085-11e7-9700-8673b56a43c6.PNG)
If move column in hidden column, and apply ,correct, next, press personalize column, focus in pagesize change to other value, and press enter (no button apply), this destroy the columns that I have moved.

**Comment by kartik-v** [comment]
Need to check this.

**Comment by kartik-v** [comment]
Cannot reproduce this on the demos page. It seems to work fine.

**Comment by metola** [comment]
Ok, I set a video.
The principal problem is that if press button Apply, the post parameter 'visibleKeys' set right,but if I press 'Enter' (keyboard) inside input pagesize, the parameter 'visibleKeys' set empty '', and save this, that is not correct.
[https://youtu.be/vULSKg8eH48](https://youtu.be/vULSKg8eH48)
