### ISSUE TITLE
Using dynagrid with TabsX makes some fields in dynagrid personalize grid setting  collapse 

### ISSUE THREAD

**Issue by mohalaika** [kartik-v/yii2-dynagrid#169]
## Steps to reproduce the issue

1.Create the tabs first:-
$items = [
    [
        'label' => 'Hold Orders',
        'content' => \Yii::$app->controller->renderPartial('hold', ['dataProvider' => $activeMed]),
        'active' => true,
        'id' => 'tab3',
    ],
    [
        'label' => 'Pending Orders',
        'content' => \Yii::$app->controller->renderPartial('pending', ['dataProvider' => $pendingMed]),
        'active' => false,
        'options' => ['id' => 'Tab1']
    ],
    [
        'label' => 'Active Orders',
       'content' => \Yii::$app->controller->renderPartial('grid', ['dataProvider' => $activeMed]),
        'active' => false,
        'id' => 'tab2',
        
    ],
   
];
echo the taps:-
echo TabsX::widget([
            'items' => $items,
            'position' => TabsX::POS_LEFT,
            'id' => '',
        ]);

it will fill the data fine,but when press on personalize grid setting for tab2 will collapse the 
Grid Theme and Default Sort selection and when press on tab3 the Page Size that related to personalize grid setting for tab 3 not exists 

#### Browsers
- [ ] Mozilla Firefox

#### Operating System

- [ ] Linux

#### Libraries

- jQuery version:
- yii2-dynagrid version:

**Comment by kartik-v** [comment]
This has nothing to do with the extensions but the way you write your markup and logic and also you need to understand the different render methods in Yii. If you are using `renderPartial` - it will just render the HTML markup but will not trigger the Javascript or Jquery scripts which are needed by plugins. You may need to do this yourself if you are using such extensions - OR use methods like `renderAjax` instead of `renderPartial`.

**Comment by mohalaika** [comment]
Yes friend I already tried your solution but still same problem,I even made changes to Yii2 advance template example adding tabs and dynagrid (clean project) and still having same problem

**Comment by mohalaika** [comment]
Dear Friend,
the reason of problem is the select components in dynagrid personalize grid setting have the same Id
I fix the issue changing on yii2-dynagrid view config.php by adding specific id for ever select in setting connection it with dynagrid Id

**Comment by kartik-v** [comment]
Thanks for the update. I will try to enhance to provide an option for configuring this. Reopening this.
