### ISSUE TITLE
Unable to have multiple dynagrid module configurations

### ISSUE THREAD

**Issue by vercotux** [kartik-v/yii2-dynagrid#170]
The ID 'dynagrid' should not be hardcoded.

**Comment by metola** [comment]
Yes, you can , in config Dynagrid you change `'options' => ['id' => $IdDynagrid]` and you can have the config for each Dynagrid

**Comment by vercotux** [comment]
@metola No you cannot. You misunderstood. I am talking about the *module* ID, not a table column.

**Comment by kartik-v** [comment]
@vercotux  your issue is not clear from the title. But the module identifier named `dynagrid` is needed in various controller actions in the Dynagrid design. 

Not sure why you would want to change the `dynagrid` module identifier to something else. If you are wondering about url or actions for the module - you can always change that using urlmanager rules within yii.

But if you are still keen on changing the module name for `dynagrid` (not sure why again) to something like `customDynagrid` you can do it this way:

** Step 1: Extend the Dynagrid Module class
```php
namespace frontend\components;
class CustomDynagridModule extends \kartik\dynagrid\Module {
    const MODULE = 'customDynagrid''
}
```

** Step 2: Define your custom dynagrid module now in yii configuration file
```php
'modules' => [
    'customDynagrid' => [ // notice this must match the MODULE constant set earlier
         'class'=>'frontend\components\CustomDynagridModule`,
    ]
]
```

**Comment by kartik-v** [comment]
I will need to understand this better. The module identifier named `dynagrid` is important for the various controller actions to work properly in the module. Can you suggest a use case why you would want the module identifier to be different. Note that if it is changing the url generated you can use Yii's URL manager rules to change the url generated for all the module actions.

**Comment by vercotux** [comment]
A few common scenarios:

 * There may already be a component or module in the app named 'dynagrid', so we cannot use this module due to naming conflicts.
 * Using a child version of the dynagrid module alongside the original dynagrid module. Also cannot do this because of hardcoded name.
 * Having multiple tables for dynagrid due to security, performance, referential integrity or other reasons. Just need to assign a different ID to each module config, but again can't since it's hardcoded.

Either way, hardcoding the ID is a "quick fix" (yii devs said this) and not a good solution as it violates the [SOLID](https://yii2-cookbook.readthedocs.io/solid/) principle. It should be avoided at all cost. It is better to allow dynamic ID and require the module to be bootstrapped in case its resources are needed from unpredictable locations.

**Comment by kartik-v** [comment]
Ok I will be providing an update for this shortly.

**Comment by kartik-v** [comment]
Now with this enhancement... you can set `Dynagrid::moduleId` to your own module id set in your configuration file (you can use relative naming for grand children). If this property is not set - it will default to `dynagrid`.

**Comment by kartik-v** [comment]
Now with [this enhancement](https://github.com/kartik-v/yii2-dynagrid/commit/eb0aca07ac04e748cb6ca3841e33020481c97cba)... you can set `Dynagrid::moduleId` to your own module id set in your configuration file (you can use relative naming for grand children). If this property is not set - it will default to `dynagrid`. Check below:

https://github.com/kartik-v/yii2-dynagrid/blob/7435f3118c8bc048d5c607e363424f57b8599746/DynaGrid.php#L71-L77

**Comment by lipin** [comment]
`yii2-dynagrid/DynaGridDetail.php &&  yii2-grid/GridView.php`
When I used it, I found it needed to add this line to the two files above, 
`public $moduleId;`
or else it would
`Setting unknown property: kartik\dynagrid\DynaGridDetail:: moduleId`
`Setting unknown property: kartik\grid\GridView:: moduleId`
Please make sure this is the case

**Comment by kartik-v** [comment]
@lipin this is not correct... you need to UPDATE your packages via COMPOSER... to ensure you get the latest release of these extensions.

**Comment by vercotux** [comment]
Sorry, took me a while to test. This is P.E.R.F.E.C.T now. Thank you for your excellent work!

**Comment by vercotux** [comment]
Spoke a little too soon. I did find one small issue, but it has a very simple fix.

You added a `moduleId` attribute to the [DynaGridSettings](https://github.com/kartik-v/yii2-dynagrid/blob/322a245d57b99e3194c0f76f6b617aef291176b0/models/DynaGridSettings.php#L34) model, which is all good, but currently it is not yet possible to configure it while it is being used inside the SettingsController, because it is being [instantiated with `new`](https://github.com/kartik-v/yii2-dynagrid/blob/322a245d57b99e3194c0f76f6b617aef291176b0/controllers/SettingsController.php#L33).

I guess there are two easy ways to fix by changing that one controller line into either:

1. `$model = new DynaGridSettings(['moduleId' => $this->module ? $this->module->id : null]);` to pass the current module id into the model, or

2. `$model = Yii::createObject(DynaGridSettings::className());` so we will be able to configure the model using dependency injection.
