### ISSUE TITLE
Missing attribute $moduleId

### ISSUE THREAD

**Issue by d4rkstar** [kartik-v/yii2-dynagrid#172]
https://github.com/kartik-v/yii2-dynagrid/blob/3e9ca029df7f7ceae3c7dd7cd923e354eae72263/DynaGridDetail.php#L119

Hello it seems that DynaGridDetail has missing $moduleId attribute

**Comment by kartik-v** [comment]
Nope... the widget definition is correct. You need to ensure you have updated packages via composer and you have the latest correct release of yii2-krajee-base.

**Comment by Bronsd** [comment]
Same error after updating. 
`Setting unknown property: kartik\dynagrid\DynaGridDetail::moduleId`
