### ISSUE TITLE
Translations for german and french

### ISSUE THREAD

**Issue by leifox** [kartik-v/yii2-dynagrid#175]
## Prerequisites

This is no issue per se but the ticket for a pull request (or the entry to help me do that).

## Steps to reproduce the issue

German translations are not complete and some are incorrect.
French translations do not exist until now.

##Help for me:
It's the first time I'm doing this, so what do I need to do next?
I have cloned the source code locally and changed the translations.

**Comment by kartik-v** [comment]
You can follow the [git workflow for contributors](https://github.com/kartik-v/yii2-dynagrid/blob/master/.github/GIT-WORKFLOW.md) as mentioned in [contribution guidelines](https://github.com/kartik-v/yii2-dynagrid/blob/master/.github/CONTRIBUTING.md).

Simpler pull requests can be done directly by editing the files online in this repo here (which will automatically fork and lead you to create a pull request).

**Comment by leifox** [comment]
As it's only simple translations, I decided to edit it directly here and submitted pull requests.
