### ISSUE TITLE
why Setting unknown property: kartik\dynagrid\DynaGridDetail::moduleId?

### ISSUE THREAD

**Issue by dfayziev** [kartik-v/yii2-dynagrid#179]
I did everything according to the documentation, and I can not understand what I'm doing wrong.
![screennnshotttt](https://user-images.githubusercontent.com/3609494/32093751-3d3223fe-bb06-11e7-9e90-cc71ee1d90a2.PNG)

first i setup in modules
    'modules' => [
		'dynagrid' => [
            'class' => '\kartik\dynagrid\Module',
            // other module settings
        ],
        'admin' => [
            'class' => 'app\modules\admin\Module',
        ],
        'gridview' => [
            'class' => '\kartik\grid\Module',
        ],
    ],

my code =  from documentation

`use kartik\widgets\DynaGrid;
use kartik\grid\GridView;
$columns = [
    ['class'=>'kartik\grid\SerialColumn', 'order'=>DynaGrid::ORDER_FIX_LEFT],
    'id',
    'name',
    [
        'attribute'=>'publish_date',
        'filterType'=>GridView::FILTER_DATE,
        'format'=>'raw',
        'width'=>'170px',
        'filterWidgetOptions'=>[
            'pluginOptions'=>['format'=>'yyyy-mm-dd']
        ],
    ],
    [
        'class'=>'kartik\grid\BooleanColumn',
        'attribute'=>'status',
        'vAlign'=>'middle',
    ],
    [
        'class'=>'kartik\grid\ActionColumn',
        'dropdown'=>false,
        'order'=>DynaGrid::ORDER_FIX_RIGHT
    ],
    ['class'=>'kartik\grid\CheckboxColumn', 'order'=>DynaGrid::ORDER_FIX_RIGHT],
];
 
echo DynaGrid::widget([
    'columns'=>$columns,
    'storage'=>DynaGrid::TYPE_COOKIE,
    'theme'=>'panel-danger',
    'gridOptions'=>[
        'dataProvider'=>$dataProvider,
        'filterModel'=>$searchModel,
        'panel'=>['heading'=>'<h3 class="panel-title">Library</h3>'],
    ],
    'options'=>['id'=>'dynagrid-1'] // a unique identifier is important
]);`

**Comment by kartik-v** [comment]
You have not updated your packages via composer and probably manually tried to update this extension. Hence you are facing the issue. Always update extension packages via composer ensuring the right dependencies are loaded. You seem to have an outdated version of a dependency `yii2-krajee-base` for yii2-dynagrid... - that is why you are facing this issue.

**Comment by dfayziev** [comment]
@kartik-v thank you very much,  i understand !!!
