### ISSUE TITLE
Move all columns - Personalize Grid Configuration

### ISSUE THREAD

**Issue by metola** [kartik-v/yii2-dynagrid#181]
Hi Kartik,

This is new enhacenment,
In the section 'Configure Order and Display of Grid Columns' it would be nice to move all Columns in the same time to visible and hidden column.
![1](https://user-images.githubusercontent.com/8111455/32889520-87ca7c70-cacb-11e7-9bc5-5c9b912ad8a3.PNG)
![2](https://user-images.githubusercontent.com/8111455/32889521-87e4056e-cacb-11e7-9af5-ec800da6fb0b.PNG)

**Comment by kidzen** [comment]
this one could be helpfull
