### ISSUE TITLE
Filtering when value is 0 not working

### ISSUE THREAD

**Issue by Geoffry304** [kartik-v/yii2-dynagrid#184]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest `master` branch of yii2-dynagrid.
- [x] This is not an usage question. I confirm having gone through and read the [documentation](http://demos.krajee.com/dynagrid) and [demos](http://demos.krajee.com/dynagrid-demo).
- [x] This is not a general programming / coding question. (Those should be directed to the [webtips Q & A forum](http://webtips.krajee.com/questions)).
- [ ] I have attempted to find the simplest possible steps to reproduce the issue.
- [ ] I have included a failing test as a pull request (Optional).

## Steps to reproduce the issue

1. Add a filter with dropdown values yes(1) and no(0) 
2. Select the no value
3. Save default filter

## Expected behavior and actual behavior

When I follow those steps, I see...
an empty array and that the value is not saved for the filter

I was expecting...
an array and that the value is saved for the filter example Approved = 0
#### Browsers

- [x] Google Chrome
- [x] Mozilla Firefox
- [x] Internet Explorer
- [ ] Safari

#### Operating System

- [x] Windows
- [x] Mac OS X
- [ ] Linux
- [ ] Mobile

#### Libraries

- jQuery version:/
- yii2-dynagrid version: latest

## Isolating the problem

- [x] This bug happens [on the demos page](https://demos.krajee.com/dynagrid-demo)
- [ ] The bug happens consistently across all tested browsers
- [x] This bug happens when using yii2-dynagrid without other plugins.

**Comment by pjalinski** [comment]
Line 1132
$model->data = array_filter($this->gridOptions['filterModel']->attributes);

change to
$model->data = array_filter($this->gridOptions['filterModel']->attributes, function($a) {return isset($a);});

**Comment by Geoffry304** [comment]
@kartik-v  is there a reason why you are not updating this?
