### ISSUE TITLE
php 7.2 compatibility

### ISSUE THREAD

**Issue by akorinek** [kartik-v/yii2-dynagrid#185]
Please change all yii\base\Object usage to \yii\base\BaseObject to enable php 7.2 compatibility.

**Comment by kartik-v** [comment]
Duplicate and resolved via #183. Check and confirm.

**Comment by vernes** [comment]
Any news when this might be in next stable release?

**Comment by SamMousa** [comment]
Are there any reasons not to release @kartik-v? Any specific issues you need help with?

**Comment by kartik-v** [comment]
Done.
