### ISSUE TITLE
Move Column in mobile view

### ISSUE THREAD

**Issue by kidzen** [kartik-v/yii2-dynagrid#186]
## Steps to reproduce the issue

1. use mobile view
2. open personalize setting and try to move column

may i suggest to use checkbox which are easier to handle
- [x] Google Chrome

#### Operating System

- [x] Windows
- [x] Mobile

#### Libraries

- yii2-dynagrid version: latest

## Isolating the problem

- [x] This bug happens [on the demos page](https://demos.krajee.com/dynagrid-demo)
- [x] The bug happens consistently across all tested browsers
- [x] This bug happens when using yii2-dynagrid without other plugins.

**Comment by neoacevedo** [comment]
I agree, this issue has over 4 years and seems it won't be viewed. In desktop, to show/hide columns is easy, not else for a mobile view where the drag/drop doesn't work.
