### ISSUE TITLE
The '' module MUST be setup in your Yii configuration file.

### ISSUE THREAD

**Issue by sayiramin** [kartik-v/yii2-dynagrid#193]
On upgrading server php version from 7.1.12 to 7.1.20 & composer update ,  all the instances of kartik-v/yii2-dynagrid  in application show an error:

Invalid Configuration – yii\base\InvalidConfigException
The '' module MUST be setup in your Yii configuration file.

## Environment:

Yii Framework/2.0.16-dev

#### Server:
PHP 7.1.20-1+ubuntu18.04.1+deb.sury.org+1 (cli)

#### Library Versions:
kartik-v/yii2-dynagrid              dev-master 8a6c7a2
kartik-v/yii2-krajee-base         dev-master a5440e5

#### Screenshot:
![screen shot 2018-09-06 at 11 51 46](https://user-images.githubusercontent.com/590056/45146726-147d4980-b1cc-11e8-9225-e34595724051.png)

**Comment by kartik-v** [comment]
You need to setup both `gridview` and `dynagrid` module as mentioned in docs.
