### ISSUE TITLE
Storing filter doesn't run

### ISSUE THREAD

**Issue by ghpeppe** [kartik-v/yii2-dynagrid#198]
## Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest `master` branch of yii2-dynagrid.
- [X] This is not an usage question. I confirm having gone through and read the [documentation](http://demos.krajee.com/dynagrid) and [demos](http://demos.krajee.com/dynagrid-demo).
- [ ] This is not a general programming / coding question. (Those should be directed to the [webtips Q & A forum](http://webtips.krajee.com/questions)).
- [X] I have attempted to find the simplest possible steps to reproduce the issue.
- [ ] I have included a failing test as a pull request (Optional).

## Steps to reproduce the issue

1. Set a filter value in a grid column. The filter is applied correctly.
2. Open the filter dialog, set a name for it and click confirm button.
3. Reset the grid removing the filter or set another filter criteria.
4. Open the filter dialog (or the personalization dialog, it's the same), select the name and click confirm button. Nothing happens.

## Expected behavior and actual behavior

The filter setting are stored correctly but they can't be restored. This happens in my application and in the demo too.
The same happens for the sorting criteria.

#### Browsers

- [X] Google Chrome
- [X] Mozilla Firefox
- [ ] Internet Explorer
- [ ] Safari

#### Operating System

- [X] Windows
- [ ] Mac OS X
- [ ] Linux
- [ ] Mobile

#### Libraries

- jQuery version:
- yii2-dynagrid version: 1.5.0

## Isolating the problem

- [X] This bug happens [on the demos page](https://demos.krajee.com/dynagrid-demo)
- [X] The bug happens consistently across all tested browsers
- [X] This bug happens when using yii2-dynagrid without other plugins.

**Comment by kartik-v** [comment]
Let me address this in following steps

1. **Creating/Saving a filter:** Let us say you wish to create a filter for blue books. On the demo select the color blue and tab. You should see only blue books. Click on the dynagrid filter icon - and save the filter as `blue books`.
2. **Checking the saved filter:** Open the filter icon again. Click the `blue books` filter to see the filter setting and verify it is fine.
3. **Personalize dynagrid to open blue books by default:** Click the dynagrid personalization wrench settings icon. Select the filter `blue books` and click apply. Click the `refresh` toolbar icon. You will see the  dynagrid always defaulting to `blue books`.
