### ISSUE TITLE
Class 'kartik\sortable\Sortable' not found

### ISSUE THREAD

**Issue by nepstor** [kartik-v/yii2-dynagrid#2]
After installation error:

``` php
PHP Fatal Error – yii\base\ErrorException
Class 'kartik\sortable\Sortable' not found
```

In file /vendor/kartik-v/yii2-dynagrid/dynagrid/views/config.php

**Comment by arsnic** [comment]
help me please. Sortable in DynaGrid does not work . 
<?=  DynaGrid::widget([
        'options'=>['id'=>'dynagrid-1'],
        'sortableOptions'=>['showHandle'=>true,
                              'type'=>'list',
                               'showHandle'=>true,
                               ],
        // 'sortableHeader'=>['class'=>'alert alert-info dynagrid-column-header'],
        'gridOptions'=>[
            'dataProvider'=>$dataProvider,
            'filterModel'=>$searchModel,
            'showPageSummary'=>false,
            'showFooter'=>false,
          //  'panel'=>'false',

        ],
        'columns'=>[
            ['class'=>'kartik\grid\SerialColumn'],

            [
                'attribute'=>'department_id',
                'width'=>'310px',
                'value'=>function ($value) {
                    return $value->department->title;
                },
                             // move grouped column to a single grouped row
              
            ],...................................................................................................

Dynagrid do work.  Sortable not.
