### ISSUE TITLE
Page Size

### ISSUE THREAD

**Issue by YairHadari** [kartik-v/yii2-dynagrid#207]
Can I change the page size of dynagrid dynamically for specific view?

**Comment by metola** [comment]
Yes, you need see the [doc](http://demos.krajee.com/dynagrid)

**Comment by YairHadari** [comment]
Metola,

Thanks for the answer.
I show the defaultPageSize, minPageSize and maxPageSize parameters.
I didn't find a way to implement them on a gridOption level.

Thanks,
Yair

**Comment by metola** [comment]
Hi YairHadari ,

Your users can dynamically change the page size value for  each view.
The parameters that you show are in module config not in Grid Option level.

I believe that this implementation is not done.

**Comment by YairHadari** [comment]
Thanks

**Comment by michalwoz** [comment]
Did I understood correctly, that we cannot set minPageSize and maxPageSize individually per single dynagrid(view) but only global config for whole module is possible?
