### ISSUE TITLE
Bootstrap4 - Class 'yii\bootstrap\Modal' not found

### ISSUE THREAD

**Issue by adamwinn** [kartik-v/yii2-dynagrid#211]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest `master` branch of yii2-dynagrid.
- [x] This is not an usage question. I confirm having gone through and read the [documentation](http://demos.krajee.com/dynagrid) and [demos](http://demos.krajee.com/dynagrid-demo).
- [x] This is not a general programming / coding question. (Those should be directed to the [webtips Q & A forum](http://webtips.krajee.com/questions)).
- [x] I have attempted to find the simplest possible steps to reproduce the issue.
- [ ] I have included a failing test as a pull request (Optional).

## Steps to reproduce the issue

1. Configure dynagrid for bootstrap4
2. Upon page view, error is thrown `Class 'yii\bootstrap\Modal' not found`

- yii2-dynagrid version:  cf0b29dc27

```Error
Class 'yii\bootstrap\Modal' not found

    1. in /Users/awinn/Documents/code/htdocs/sbpv4/vendor/kartik-v/yii2-dynagrid/src/views/config.php at line 65
    56575859606162636465666768697071727374

                        <?php
    /**
     * @var \yii\bootstrap\Modal $modalClass
     */
    $modalClass = $isBs4 ? 'yii\bootstrap4\Modal' : 'yii\bootstrap\Modal';
    $hdr = $iconPersonalize . ' ' . Yii::t('kvdynagrid', 'Personalize Grid Configuration');
    $modalOpts = [
        'footer' => $model->footer,
        'toggleButton' => $toggleButtonGrid,
        'size' => Modal::SIZE_LARGE,
        'options' => ['id' => $id],
    ];
    if ($isBs4) {
        $modalOpts['title'] = $hdr;
    } else {
        $modalOpts['header'] = '<h3 class="modal-title">' . $hdr . '</h3>';
    }
    $modalClass::begin($modalOpts);
    ?>
```

`Modal::SIZE_LARGE` is referring to the bootstrap3 version of SIZE_LARGE and it cannot be found if only bootstrap4 is installed

**Comment by kartik-v** [comment]
You need to setup the Bootstrap version for Krajee Widgets. Read [the documentation](http://demos.krajee.com/dynagrid#bs-info) for Dynagrid Bootstrap version setup.

**Comment by adamwinn** [comment]
I already read the docs and setup dynagrid.

```
'dynagrid'=>[
            'class'=>'\kartik\dynagrid\Module',
            'defaultPageSize'=>50,
            'maxPageSize'=>200,
            'bsVersion'=>'4.x',
        ],
```
I had to change `use yii\bootstrap\Modal` to `use yii\bootstrap4\Modal`

**Comment by kartik-v** [comment]
I see. I understand the issue (it is in the views file - will check and update).

**Comment by kartik-v** [comment]
Fixed via latest update. Cross check and let know.

**Comment by adamwinn** [comment]
It's fixed! Thanks
