### ISSUE TITLE
Sort (asc and desc) icons are broken

### ISSUE THREAD

**Issue by adamwinn** [kartik-v/yii2-dynagrid#212]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest `master` branch of yii2-dynagrid.
- [x] This is not an usage question. I confirm having gone through and read the [documentation](http://demos.krajee.com/dynagrid) and [demos](http://demos.krajee.com/dynagrid-demo).
- [x] This is not a general programming / coding question. (Those should be directed to the [webtips Q & A forum](http://webtips.krajee.com/questions)).
- [ ] I have attempted to find the simplest possible steps to reproduce the issue.
- [ ] I have included a failing test as a pull request (Optional).

## Steps to reproduce the issue
When using dynagrid and clicking on a header to sort, the asc/desc icon shows up as a weird box.  This doesn't happen on the demo page.

```
use yii\helpers\Html;
use yii\helpers\Url;
use kartik\dynagrid\DynaGrid;
use kartik\grid\GridView;
use kartik\icons\Icon;
Icon::map($this, Icon::FAS);
use yii\widgets\Breadcrumbs;
use kartik\icons\FontAwesomeAsset;
FontAwesomeAsset::register($this);

<div class="event-items-index">

<?php

echo DynaGrid::widget([
    'storage'=>DynaGrid::TYPE_DB,
    'columns' => $columns,
    'theme'=>'panel-primary',
    'showPersonalize'=>true,
    'gridOptions'=>[
        'pjaxSettings' => [
            'loadingCssClass' => false,
        ],
        'condensed'=>true,
        'striped'=>true,
        'pjax'=>true,
        'dataProvider'=>$dataProvider,
        'filterModel'=>$searchModel,
        'panel'=>[
            'heading'=>Icon::show('list-alt').'  Event Items',
            'before' => Html::button(Icon::show('upload').'Upload Store Qtys', ['type'=>'button', 'title'=>'Upload Store Qtys', 'class'=>'btn btn-outline-primary']).'&nbsp;&nbsp;'.
                        Html::button(Icon::show('plus').'Add Item', ['type'=>'button', 'title'=>'Add Item', 'class'=>'btn btn-outline-primary']).'&nbsp;&nbsp;'.
                        Html::button(Icon::show('file-excel').'Create Output File', ['type'=>'button', 'title'=>'Create Output File', 'class'=>'btn btn-outline-primary'])
        ],
        'toolbar' =>  [
            ['content'=>''],
            ['content'=>'{pager}&nbsp;'.Html::a(Icon::show('redo'), ['/event-item?event_id='.$event_model->event_id], ['data-pjax'=>0, 'class' => 'btn btn-outline-secondary', 'title'=>'Reset Grid']).'&nbsp;{dynagridFilter}&nbsp;{dynagridSort}&nbsp;{dynagrid}&nbsp;{export}'],
        ]
    ],
    'options'=>['id'=>'event-item-grid'] // a unique identifier is important
]);
```

## actual behavior

[browser](https://imgur.com/a/aXDFhqo)
[console](https://imgur.com/a/Qc9vAqv)

#### Browsers

- [x] Google Chrome
- [x] Mozilla Firefox
- [ ] Internet Explorer
- [ ] Safari

#### Operating System

- [ ] Windows
- [x] Mac OS X
- [ ] Linux
- [ ] Mobile

#### Libraries

- jQuery version:  v3.2.1
- yii2-dynagrid version: dev-master 16b9f2b

## Isolating the problem

- [ ] This bug happens [on the demos page](https://demos.krajee.com/dynagrid-demo)
- [x] The bug happens consistently across all tested browsers
- [ ] This bug happens when using yii2-dynagrid without other plugins.

**Comment by adamwinn** [comment]
I fixed this by doing
```
Option 1: Font CSS version of Font Awesome:

<!-- on your view layout file HEAD section -->
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.3.1/css/all.css">
```

I had previously done the alternative part to Option 2, as shown in my setup above, but that didn't work
```
    Option 2: SVG / JS version of Font Awesome (recommended for cleaner scaling vector icons and features like icon layers):

    <!-- on your view layout file HEAD section -->
    <script defer src="https://use.fontawesome.com/releases/v5.3.1/js/all.js" crossorigin="anonymous"></script>

    Alternatively, you can use the FontAwesomeAsset from the kartik-v/yii2-icons package to load the SVG/JS version.

    // on your view layout file
    use kartik\icons\FontAwesomeAsset;
    FontAwesomeAsset::register($this);
```

**Comment by kartik-v** [comment]
Yes its because Yii2 grid by default uses the CSS method to inject the ICON content after the header title.

If using FontAwesomeAsset (it uses Font awesome JS and SVG) - you need to write your own JS code or additional css to embed the icons.
