### ISSUE TITLE
Low performance compared to \yii\grid\GridView

### ISSUE THREAD

**Issue by sokollondon** [kartik-v/yii2-dynagrid#222]
Page loads maсh slower when use \kartik\dynagrid\DynaGrid instead \yii\grid\GridView
Especially if several grid on the page.
Maybe add the ability to cache settings when storage is DynaGrid::TYPE_DB? Or somehow optimize

#### Libraries

- yii2-dynagrid version: 1.5.1.0

**Comment by kartik-v** [comment]
Should be a part of your app code design typically to handle display of many dynagrids that will run multiple DB queries running. Also note that dynagrid does offer other storage methods like SESSION and COOKIE... however caching typically can be handled via your yii2 app cache settings for such use cases.

Am open to suggestions - let know.
