### ISSUE TITLE
The '' module MUST be setup in your Yii configuration file.

### ISSUE THREAD

**Issue by adamwinn** [kartik-v/yii2-dynagrid#229]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest `master` branch of yii2-dynagrid.
- [x] This is not an usage question. I confirm having gone through and read the [documentation](http://demos.krajee.com/dynagrid) and [demos](http://demos.krajee.com/dynagrid-demo).
- [x] This is not a general programming / coding question. (Those should be directed to the [webtips Q & A forum](http://webtips.krajee.com/questions)).
- [x] I have attempted to find the simplest possible steps to reproduce the issue.
- [ ] I have included a failing test as a pull request (Optional).

## Steps to reproduce the issue
I followed the docs and have this code but I get an error message
```
// fetches grid configuration
$store = new DynaGridStore([
    'id' => $this->options['id'], 
    'storage' => 'db',
    'userSpecific' => true,
    'category' => 'grid'
]);
return $store->fetch();
```
## Expected behavior and actual behavior
```
Invalid Configuration – yii\base\InvalidConfigException
The '' module MUST be setup in your Yii configuration file.
```
The docs dont mention setting up the DynaGridStore module

I put this in and I still got the same message
```
    'modules' => [
        'dynagrid'=>[
            'class'=>'\kartik\dynagrid\Module',
            'defaultPageSize'=>200,
            'maxPageSize'=>1000,
        ],
        'dynagridstore'=>[
            'class'=>'\kartik\dynagridstore\Module',
        ],
        'gridview' =>  [
            'class' => '\kartik\grid\Module'
        ],
    ],
```
There seems to also be a bug in the error message as `""` is empty

**Comment by adamwinn** [comment]
This issue is still happening

**Comment by adamwinn** [comment]
@kartik-v Please re-open this issue

**Comment by asamats** [comment]
```
$store = new DynaGridStore([
            'moduleId' => 'dynagrid',
            'id' => self::ID,
            'storage' => DynaGrid::TYPE_COOKIE,
            'userSpecific' => true,
            'category' => DynaGridStore::STORE_FILTER,
        ]);
```
where `moduleId` must be the key that is used in config
```
    'modules' => [
        'dynagrid' => \kartik\dynagrid\Module::class,
        'gridview' => \kartik\grid\Module::class,
    ],
```
