### ISSUE TITLE
Enable Cache on DynaGridStore

### ISSUE THREAD

**Issue by alexforte** [kartik-v/yii2-dynagrid#232]
## Prerequisites

- [X ] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X ] The issue still exists against the latest `master` branch of yii2-dynagrid.
- [X] This is not an usage question. I confirm having gone through and read the [documentation](http://demos.krajee.com/dynagrid) and [demos](http://demos.krajee.com/dynagrid-demo).
- [ ] This is not a general programming / coding question. (Those should be directed to the [webtips Q & A forum](http://webtips.krajee.com/questions)).
- [X] I have attempted to find the simplest possible steps to reproduce the issue.
- [ ] I have included a failing test as a pull request (Optional).

## Steps to reproduce the issue

1. Go to a page where is present DynaGrid
2. Checkout the Debugger Tool and u'll see at least 2 Duplicates of the same Query on DynaGridStore

## Expected behavior and actual behavior

I was expecting that DynaGridStore is stored in Cache because doesn't change so often.

#### Browsers

- [X] Google Chrome
- [X] Mozilla Firefox
- [X] Internet Explorer
- [X] Safari

#### Operating System

- [X] Windows
- [X] Mac OS X
- [X] Linux
- [X] Mobile

#### Libraries

- jQuery version:
- yii2-dynagrid version:

## Possible Solution:
I found a solution that i want share with all community.
In row 415 of DynaGridStore.php you can change to this:

// Original
// $data = (new Query())
//     ->select([$s['idAttr'], $s['nameAttr']])
//     ->from($s['tableName'])
//     ->where([$s['dynaGridIdAttr'] => $this->_mstKey, $s['categoryAttr'] => $cat])
//     ->all(Yii::$app->$connection);

// Fix Problem
$data = Yii::$app->getDb()->cache(function ($connection) use ($s) 
                { 
                    $data = (new Query())
                    ->select([$s['idAttr'], $s['nameAttr']])
                    ->from($s['tableName'])
                    ->where([$s['dynaGridIdAttr'] => $this->_mstKey, $s['categoryAttr'] => $cat])
                    ->all($connection);
                    return $data;
                });

**Comment by kartik-v** [comment]
Thanks for the suggestion. Could you submit a PR?
