### ISSUE TITLE
defaultPageSize overrides dataProvider pageSize setting

### ISSUE THREAD

**Issue by spo0okie** [kartik-v/yii2-dynagrid#241]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest `master` branch of yii2-dynagrid.
- [x] This is not an usage question. I confirm having gone through and read the [documentation](http://demos.krajee.com/dynagrid) and [demos](http://demos.krajee.com/dynagrid-demo).
- [x] This is not a general programming / coding question. (Those should be directed to the [webtips Q & A forum](http://webtips.krajee.com/questions)).
- [x] I have attempted to find the simplest possible steps to reproduce the issue.
- [ ] I have included a failing test as a pull request (Optional).

## Steps to reproduce the issue

1. create dataProvider with 'pagination' => ['pageSize' => 100],
2. render dynaGrid widget with no pagination settings in widget or persionalized settings

## Expected behavior and actual behavior

When I follow those steps, I see...
  pagesize of 10 (as default set in module settings)

I was expecting...
  pagesize of 100 (as set in dataprovider) because default settings must not override customized

#### Browsers

- [x] Google Chrome
- [x] Mozilla Firefox
- [ ] Internet Explorer
- [ ] Safari

#### Operating System

- [x] Windows
- [ ] Mac OS X
- [x] Linux
- [ ] Mobile

#### Libraries

- jQuery version: 3.6.0
- yii2-dynagrid version: 1.5.4

## Isolating the problem

- [ ] This bug happens [on the demos page](https://demos.krajee.com/dynagrid-demo)
- [x] The bug happens consistently across all tested browsers
- [ ] This bug happens when using yii2-dynagrid without other plugins.

Problem is isolated in widget initialization (initWidget(), DynaGrid.php, row 619):

```
if (!isset($this->_pageSize) || $this->_pageSize === null) {
    $this->_pageSize = $this->_module->defaultPageSize;
}
```
no $dataProvider attrs used. and next in row 637 
```
$this->applyGridConfig();
```
then in row 776
```
$this->applyPageSize();
```
which finaly override $dataProvider pagination with new (simply default value) pageSize

i think it must be first attempt to read pageSize from $dataProvider in rows 619-621 and then use of defaultPageSize as fallback (if no custom value is set)

**Comment by csatarij** [comment]
I am facing the exact same issue but updating to version v1.5.5 is not solving it.
Shall I open a new bug with all the details?
