### ISSUE TITLE
Save/Edit Grid filter and sort has UI issues

### ISSUE THREAD

**Issue by newadventure079** [kartik-v/yii2-dynagrid#243]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest `master` branch of yii2-dynagrid.
- [x] This is not an usage question. I confirm having gone through and read the [documentation](http://demos.krajee.com/dynagrid) and [demos](http://demos.krajee.com/dynagrid-demo).
- [x] This is not a general programming / coding question. (Those should be directed to the [webtips Q & A forum](http://webtips.krajee.com/questions)).
- [ ] I have attempted to find the simplest possible steps to reproduce the issue.
- [ ] I have included a failing test as a pull request (Optional).

## Steps to reproduce the issue

1. Go to the dynagrid demo page and use the save sort or save filter option
2. Look at the UI modal and notice UI weirdness with extra space and ' marks

![Screenshot 2023-07-30 at 12 10 47 PM](https://github.com/kartik-v/yii2-dynagrid/assets/84156407/507273c7-eec8-4c8e-b5ed-0134fb2160db)

![Screenshot 2023-07-30 at 12 13 38 PM](https://github.com/kartik-v/yii2-dynagrid/assets/84156407/32f0cf96-84b4-4a41-91b6-d454a77b72e8)

#### Browsers

- [x] Google Chrome
- [ ] Mozilla Firefox
- [ ] Internet Explorer
- [ ] Safari

#### Operating System

- [ ] Windows
- [x] Mac OS X
- [ ] Linux
- [ ] Mobile

#### Libraries

- jQuery version: demo page version
- yii2-dynagrid version: demo page version

## Isolating the problem

- [x] This bug happens [on the demos page](https://demos.krajee.com/dynagrid-demo)
- [x] The bug happens consistently across all tested browsers
- [x] This bug happens when using yii2-dynagrid without other plugins.

**Comment by kartik-v** [comment]
Seems this issue does not exist anymore. Let know if any other issue and open it up separately.
