### ISSUE TITLE
Sort and Filter delete modals are hidden

### ISSUE THREAD

**Issue by newadventure079** [kartik-v/yii2-dynagrid#244]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest `master` branch of yii2-dynagrid.
- [x] This is not an usage question. I confirm having gone through and read the [documentation](http://demos.krajee.com/dynagrid) and [demos](http://demos.krajee.com/dynagrid-demo).
- [x] This is not a general programming / coding question. (Those should be directed to the [webtips Q & A forum](http://webtips.krajee.com/questions)).
- [ ] I have attempted to find the simplest possible steps to reproduce the issue.
- [ ] I have included a failing test as a pull request (Optional).

## Steps to reproduce the issue

1.  Bring up the filter or sort modal
2.  Delete a saved filter or sort
3.  Notice the confirmation modal is behind the filter/sort modal and is not visible

 

https://github.com/kartik-v/yii2-dynagrid/assets/84156407/f330b208-db2f-4ef8-993f-aa764cdee250

#### Browsers

- [x] Google Chrome
- [ ] Mozilla Firefox
- [ ] Internet Explorer
- [ ] Safari

#### Operating System

- [ ] Windows
- [x] Mac OS X
- [ ] Linux
- [ ] Mobile

#### Libraries

- jQuery version: demo version
- yii2-dynagrid version: demo version

## Isolating the problem

- [x] This bug happens [on the demos page](https://demos.krajee.com/dynagrid-demo)
- [x] The bug happens consistently across all tested browsers
- [x] This bug happens when using yii2-dynagrid without other plugins.

**Comment by kartik-v** [comment]
Seems this issue does not exist anymore. Let know if any other issue and open it up separately.
