### ISSUE TITLE
Uncaught TypeError: Cannot read property 'outerWidth' of undefined

### ISSUE THREAD

**Issue by iviu96afa** [kartik-v/yii2-dynagrid#47]
I'm always getting this error in chrome console after I search in dynagrid. you can catch it even in you demo page http://demos.krajee.com/dynagrid-demo

**Comment by fwroman** [comment]
I have the same problem with kartik gridview ExpandRowColumn, your solutions is already in GridView.php of kartik-grid, this line is included 

````php
 $postPjaxJs = "setTimeout({$this->_gridClientFunc}(), 2500);";
````
I'm using Tabx with two items to render a gridview inside of each one, the problem appears when I click the expandRowColumn contained in tabx item with **active = false** attribute, I'm using pjax to filter data in the gridview too...

Next code is triggered when the page is already loaded, to submit the data filtered:

````php
$.pjax.reload({container:"#pjaxResumenInvImp"});
````
