### ISSUE TITLE
Problems with displaying summary

### ISSUE THREAD

**Issue by arogachev** [kartik-v/yii2-dynagrid#53]
The following code:

```php
<?= DynaGrid::widget([
    ...
    'gridOptions' => [
        ...
        'showPageSummary' => true,
    ],    
]) ?>
```

generates this HTML output:

```html
<tfoot>
    <tr class="kv-page-summary warning">
        <td style="width:50px;" class="kv-align-center kv-align-middle">&nbsp;</td>
        <td>&nbsp;</td>
        <td>&nbsp;</td>
        <td>&nbsp;</td>
        <td>&nbsp;</td>
        <td>&nbsp;</td>
        <td>&nbsp;</td>
    </tr>
</tfoot>
```

What's wrong?

**Comment by kartik-v** [comment]
There's nothing wrong... [read docs for page summary](http://demos.krajee.com/grid#page-summary) ... `showPageSummary` just enables the page summary row for display.

You need to set what you want to display in page summary for each grid DataColumn. [Read docs for DataColumn](http://demos.krajee.com/grid#data-column) - check the `pageSummary` and `pageSummaryFunc` properties within each column setting.

**Comment by arogachev** [comment]
I actually want to display summary of records on this page / total. How I can do that? Can't find it in the docs and seems like it's disabled by default.

**Comment by kartik-v** [comment]
Check my comment before

> You need to set what you want to display in page summary for each grid DataColumn. [Read docs for DataColumn](http://demos.krajee.com/grid#data-column) - check the `pageSummary` and `pageSummaryFunc` properties within each column setting.


Check the [grid demo](http://demos.krajee.com/grid-demo) page if you need the code example of page summary - check the configuration for the grid columns which have the total/summary enabled.

**Comment by arogachev** [comment]
No, I actually want to show this: `Showing 1-10 of 20 items.`. Can't find option for that and it's disabled by default. Sorry that I didn't mention these details earlier.

**Comment by arogachev** [comment]
The problem still is not solved. I think it's somehow related with `theme` setting. How I can add this line?

**Comment by kartik-v** [comment]
What you are talking about is not the page summary but the pagination links. You may check the core yii grid docs. This is rendered using the `{pager}` tag .

The default grid theme renders it in the panel. If you are not seeing it you may have chosen a different template/theme. Your grid template must have the `{pager}` tag somewhere to render this.

In general I would suggest reading the docs thoroughly. Read about [layout templates in the yii2-grid docs](http://demos.krajee.com/grid#layout-templates).

**Comment by arogachev** [comment]
It's not pager.

`{summary}`: string, which will render the grid results summary.

**Comment by arogachev** [comment]
I tried to apply settings from the demo (except `columns`), but this line is not shown: `Showing 1-10 of 20 items`, while in demo it's shown.

**Comment by kartik-v** [comment]
If you are using dynagrid - it will depend on what theme you are using. If you are using the default theme as in the demo - you should be able to see.

**Comment by arogachev** [comment]
Yes, i'm using the same exact theme: `'theme' => 'panel-info',`, `gridOptions` are the same too. The summary still is Not shown.

**Comment by kartik-v** [comment]
Note that yii will show pagination summary only if number of records exceed ONE PAGESIZE.

So if you have 5 records and your pagesize is 10 you will not see the page summary.

**Comment by arogachev** [comment]
Sorry, my bad, it was hidden because of used css. Thanks for the help.
