### ISSUE TITLE
Grid not saving when allowThemeSetting is false

### ISSUE THREAD

**Issue by dudunegrinhu** [kartik-v/yii2-dynagrid#54]
Kartik,

I did the update by getting the code from dev-master but when I put 'allowThemeSetting' => false, than the grid doesn't save my changes that I did on the Personalize Grid Configuration screen.
If I remove allowThemeSetting than it works.

**Comment by dudunegrinhu** [comment]
Kartik do you have any update on this issue?

**Comment by kartik-v** [comment]
It does work fine on my tests without `allowThemeSetting` property.

Note that the `theme` is a required attribute in the `DynaGridConfig` model. It defaults to the `kartik\dynagrid\Module::defaultTheme` setting. So ensure you have this value set if you have overridden it in your themes.

**Comment by dudunegrinhu** [comment]
Karthik,

This is my configuration and still didn't work.

DynaGrid::widget([
	    	'columns' => $gridColumns,
	    	'theme'=>'panel-info',
		'showPersonalize'=>true,
		'storage'=>'cookie',
	    	'showFilter' => false,
	    	'showSort' => false,
	    	'showPersonalize' => true,
	    	'allowFilterSetting' => false,
	    	'allowSortSetting' => false,
	    	'allowThemeSetting' => false,
	    	'gridOptions'=>[
	    		'dataProvider'=>$dataProvider,
	    		'filterModel'=>$searchModel,
	    		'filterSelector' => '#searchModel',
	    		'showPageSummary'=>true,
		        'bordered' => true,
		    	'striped' => true,
		    	'bootstrap' => true,
		    	'condensed' => true,
		    	'responsive' => true,
		    	'floatHeader' => true,	    		
		        'pjax'=>true,
	    		'resizableColumns' => true,
	    		'panel'=>[
	            	'heading' => '<i class="fa fa-location-arrow"></i> Locations List',
	    			'before' => '<div class="input-group">
	    							<span class="input-group-addon"><i class="fa fa-search"></i></span>
	    							<input type="text" placeholder="Search..." name="LocationSearch[name]" id="searchModel" class="form-control width99">
	    						</div>',
		            'after' => false
	            ],
	    		'toolbar' =>  [
		    		['content'=>
		    			Html::a('<i class="glyphicon glyphicon-repeat"></i> Refresh Grid', ['index'], ['class' => 'btn btn-info'])
		    		],
	    			['content'=>'
	    				{dynagrid}'
	    			],
	    		],
	    	],
	    	'options'=>['id'=>'dynagrid-location-list']
	    ]);

**Comment by kartik-v** [comment]
Ok I am providing an enhancement to fix this shortly.

**Comment by kartik-v** [comment]
You can check with updated code from dev-master now.
