### ISSUE TITLE
Please add ajax fontsize selection in toolbar

### ISSUE THREAD

**Issue by ScottHuangZL** [kartik-v/yii2-dynagrid#55]
Some times we try to minimize the fontsize in case we have lots of columns need to display in grid.
I am using my customized ajax function to dyna adjust fontsize for dynagrid now.

Would suggest you direct provoide this function for dynagrid widget.
Such as a dropdown list allow user to select huge/large/normal/small/tiny(140%/120%/100%/85%/70%) fontsize and then dynagrid change its all fontsize style immediately with ajax.

**Comment by kartik-v** [comment]
You could do it with themes... like LARGE, MEDIUM, SMALL...
