### ISSUE TITLE
Get Selected Rows

### ISSUE THREAD

**Issue by dudunegrinhu** [kartik-v/yii2-dynagrid#58]
Kartik,

Sorry to open an issue for this but I'm trying for almost month already and with no success.
I need to get the selected rows (checkbox) so I can export or do whatever I can do with all the selected rows.

Can you help me please?

**Comment by kartik-v** [comment]
Hope you have read the default yii guide. You may once want to do that.

This is addressed in [yii\grid\CheckboxColumn](http://www.yiiframework.com/doc-2.0/guide-output-data-widgets.html#checkbox-column)... you need to write your javascript accordingly.

The selected rows may be obtained by calling the following JavaScript code:

```js
var keys = $('#grid').yiiGridView('getSelectedRows');
// keys is an array consisting of the keys associated with the selected rows
```

**Comment by dudunegrinhu** [comment]
@kartik-v I already tried that but it gives me an error:

TypeError: $(...).yiiGridView is not a function

**Comment by kartik-v** [comment]
The error means you are using a wrong identifier for your grid. The HTML ID attribute must pertain to your gridview container.

For Dynagrid you access the grid ID through `gridOptions['options']['id']`.... you need to set a value for this and access.

**Comment by kartik-v** [comment]
The error means you are using a wrong identifier for your grid. The HTML ID attribute must pertain to your gridview container.

For Dynagrid you set gridview widget properties via `gridOptions` - hence you can access the grid ID attribute through `gridOptions['options']['id']`. You may need to set a value for this and access. For example:

```php
// widget php script
echo Dynagrid::widget([
    'gridOptions' => ['options' => ['id' => 'grid']],
    // other options
]);
```

Then access the same via javascript.
```js
// js script
var keys = $('#grid').yiiGridView('getSelectedRows');
// keys is an array consisting of the keys associated with the selected rows
```

**Comment by dudunegrinhu** [comment]
@kartik-v if I do this:

'gridOptions'=>['options' => ['id' => 'grid']
I get this error: You must setup a unique identifier for DynaGrid within "options['id']".

but If I put this:

'gridOptions'=>[
	    		'dataProvider'=>$dataProvider,
....
],
'options'=>['id'=>'grid']

than doesn't give me an error but the javascript doesn't work. I posted the code everyone, forums, google, everywhere. Please help me. Does Dynagrid support the yiiGridView('getSelectedRows') ?

**Comment by kartik-v** [comment]
I do not understand why this is so difficult for you. Do not just blindly copy my code... you need to provide all widget settings as required by Dynagrid - as I mentioned in the code comment:

// widget php script
echo Dynagrid::widget([
   'options' => ['id' => 'dynagrid'], // this is dynagrid identifier
    'gridOptions' => ['options' => ['id' => 'grid']], // this is gridview identifier
    // add other settings required by DYNAGRID
]);

**Comment by dudunegrinhu** [comment]
Sorry @kartik-v it worked now, it was a conflict name on both id's.
Thanks for the clarification. I would like to make a donation to you because I'm using a lot of your components and if you have the time I would like to hire you as a consultant.

**Comment by ikramadjissa** [comment]
I get this error : 
Setting unknown property: kartik\grid\GridView::gridOptions

**Comment by mohalaika** [comment]
thanks a lot it's working fine
but if you may how I get the full row data using the key?
