### ISSUE TITLE
Only Sort instance, configuration array or false is allowed.

### ISSUE THREAD

**Issue by philippfrenzel** [kartik-v/yii2-dynagrid#64]
368369370371372373374375376377378379380            'id' => $this->options['id'],
            'storage' => $this->storage,
            'userSpecific' => $this->userSpecific
        ]);
        $this->prepareColumns();
        $this->configureColumns();
        $this->applyGridConfig();
        $this->_isPjax = ArrayHelper::getValue($this->gridOptions, 'pjax', false);
        if ($this->_isPjax) {
            $this->gridOptions['pjaxSettings']['options']['id'] = $this->_pjaxId;
        }
        $this->initGrid();

**Comment by philippfrenzel** [comment]
latest dyngrid and yii2... migrated from a version like around 6 weeks ago!

**Comment by kartik-v** [comment]
Not clear with this query. What is the issue?

**Comment by philippfrenzel** [comment]
since the latest update, the storage::db -> is returning an error! Which means a sort which is stored will not be loaded correrctly and applied to the grid

**Comment by philippfrenzel** [comment]
Thanks so much! +1+
