### ISSUE TITLE
Uncaught ReferenceError: initSelect2Loading is not defined

### ISSUE THREAD

**Issue by philippfrenzel** [kartik-v/yii2-dynagrid#65]
While grid pjax setting is true and I'm using a select2 within filter, I recieve the following error message:

Uncaught ReferenceError: initSelect2Loading is not defined

**Comment by kartik-v** [comment]
You need to update to latest releases of all Krajee extensions to ensure you have consistent versions.

**Comment by kartik-v** [comment]
Just realized latest release v1.4.4 was not tagged --- its done now.
