### ISSUE TITLE
Composer dependencies.

### ISSUE THREAD

**Issue by SamMousa** [kartik-v/yii2-dynagrid#67]
Hi,

We are in the process of specifying proper version dependencies so we only include stable third party code.
I noticed that while all your libraries (which we appreciate immensely) use proper tagging for versioning, however their dependencies do not.
For example dynagrid lists a lot of dependencies as *, shouldn't the dependency at least require a specific major version?

Cheers,

**Comment by kartik-v** [comment]
Technically correct. Will do when I get time - or you can help with a PR.

However in many cases, there is less dependency on versions. For example, or `yii2-dynagrid` depends on `yii2-widget-select2` but any version of `yii2-widget-select2`  will work with `yii2-dynagrid`.
