### ISSUE TITLE
Dynagrid install

### ISSUE THREAD

**Issue by htsnorman** [kartik-v/yii2-dynagrid#68]
Hi!

I just started practicing yii2 and found the add-ons and you are very good but I can not do anything

dynagrid, every step has been done. I do not agree at the end (Usage)

Kartik use \ widgets \ DynaGrid;
Kartik use \ grid \ GridView;
$ columns = [
     ['class' => 'Kartik \ grid \ SerialColumn', 'order' => DynaGrid :: ORDER_FIX_LEFT]
     'id'
     'name',
     [
         'attribute' => 'PUBLISH_DATE'

where and how to use these lines?

(I tried this application I created (index.php))

Sorry for my bad english :) :+1:

**Comment by kartik-v** [comment]
You need to do some reading on Yii and namespaces. 

On the DynaGrid module [read documentation](http://demos.krajee.com/dynagrid) and how you set it up. 

Your use statements are incorrect... and you are using an invalid/wrong namespace for DynaGrid ... it must be `use kartik\dynagrid\Dynagrid;`
