### ISSUE TITLE
InitSelect2Loading should be InitS2Loading

### ISSUE THREAD

**Issue by joester89** [kartik-v/yii2-dynagrid#69]
In https://github.com/kartik-v/yii2-dynagrid/blob/master/assets/js/kv-dynagrid.js#L127 InitSelect2Loading is used though this function is not defined. I think it should be InitS2Loading.

**Comment by YasserHassan** [comment]
@joester89 clearing your published assets might fix this.

**Comment by joester89** [comment]
@YasserHassan, already tried that but the called function doesn't exist in the source.
