### ISSUE TITLE
Remove column from toggleData (Hidden / Fixed Columns)

### ISSUE THREAD

**Issue by andjelko** [kartik-v/yii2-dynagrid#82]
I extend class Dynagrid 

function setWidgetColumns

replace code
<pre>
            if(!$column['noshow']) /// add this line
            { /// add this line
                $widgetColumns = [
                    'content' => (empty($indicator) ? '' : $indicator . ' ') . $this->getColumnLabel($key, $column),
                    'options' => ['id' => $key]
                ];

                if ($showAll && !$disabled) {
                    $visibleSettings[$key] = $widgetColumns;
                } elseif (in_array($key, $this->_visibleKeys) && !$disabled) {
                    $visibleSettings[$key] = $widgetColumns;
                } else {
                    $this->_hiddenColumns[] = $widgetColumns + ['disabled' => $disabled];
                }
            } /// add this line
</pre>
and when i set parameter "noshow" to 0 that column are not show

**Comment by kartik-v** [comment]
If you have a suggestion for enhancement - please raise a pull request. Not clear with this query.
