### ISSUE TITLE
The scroll will be inconvenient in case have many columns in dynagrid

### ISSUE THREAD

**Issue by ScottHuangZL** [kartik-v/yii2-dynagrid#85]
I like dynagrid.
However, I encounter one issue is the scroll not convenient in case the grid have many columns.
You have to go down firstly, find the scroll bar in pane which above the pages, and pull right to scroll columns.
And it always confuse since there will be 2 scroll bar, one is pane itself, the other is browser. 

The root cause is the dynagrid only display grid within the pane with same size as your screen.

Can you provide a flag to allow display the grid wide than screen? In short, only one horizontal scroll bar in browser to avoid confusion.

**Comment by kartik-v** [comment]
Not sure what the flag will do. You can style what you want for your markup through your own additional CSS.

You already can set the grid CSS classes and  table css Classes e.g. via `tableOptions`.
