### ISSUE TITLE
Bug in InternetExplorer 10+ when no results where found

### ISSUE THREAD

**Issue by dvdkrgr** [kartik-v/yii2-dynagrid#86]
Hey, I've found the following bug:
When you do a search that will return zero results it will hide the "No results found" label behind the floating headers like in this screenshot (it only appears after a few seconds!):

![unbenannt](https://cloud.githubusercontent.com/assets/11403884/8845673/5dfc9e00-3121-11e5-9791-dfae95ec7b8c.PNG)

This errors seems to be only in the dynagrid, the normal gridview is not doing it:
![unbenannt](https://cloud.githubusercontent.com/assets/11403884/8845759/1334e5fc-3122-11e5-86ca-37123f88fdb3.PNG)

This happends in IE 10 + 11 to me. IE 9 is fine.

**Comment by kartik-v** [comment]
If you do not want table headers to float across the page, then set `floatHeader` to `false` in gridOptions.
