### ISSUE TITLE
i18n: Name of ActionColumn in settings-dialog

### ISSUE THREAD

**Issue by stjcottbus** [kartik-v/yii2-dynagrid#90]
Hi again.

An ActionColumn renders with localized column-title (e.g. 'Aktionen' for 'Actions' in German).

In configuration-dialog it is always displayed as 'Action Column' which is disturbing for users which uses other languages. 
Is there a way to use the same Value as used for the column-title in the Grid?

**Comment by kartik-v** [comment]
You must set the `header` property for the `ActionColumn`.

**Comment by stjcottbus** [comment]
Thanks.
