### ISSUE TITLE
EditableColumn does not work when two grid are displayed

### ISSUE THREAD

**Issue by ber5ien** [kartik-v/yii2-dynagrid#91]
I have two grid displayed on the page their display the info from the table.

If first grid 1 have got 3 rows then first 3 in grid 2 cannot be edited. They shows as editable but when you click on it nothing happens.

Grid Settings:

$availableGrid = DynaGrid::begin([
    'id' => '1',    
    'columns'=>$available,
    'theme'=>'panel-info',
    'showPersonalize'=>true,
    'storage'=>'db',   
    'gridOptions'=>[
        'dataProvider'=>$dataProviderAvailable,        
        'filterModel'=>$searchModel,
        'showPageSummary'=>false,
        'floatHeader'=>true,
        'pjax'=>true,  //the entire GridView widget will be parsed via Pjax and rendered inside a yii\widgets\Pjax widget container
        'pjaxSettings'=>[
            'refreshGrid' => true,
            'neverTimeout'=>true,
            'options' => ['id' => '1'],
  'options'=>['id'=>'dynagrid-1'] // a unique identifier is important

$dynagrid = DynaGrid::begin([
    'id' => '2',    
    'storage'=>'db',   
    'columns'=>$userTicketView,
    'theme'=>'panel-info',
    'showPersonalize'=>true,    
    'gridOptions'=>[        
        'dataProvider'=>$dataProvider,
        'filterModel'=>$searchModel,        
        'floatHeader'=>false,
        'pjax'=>true,  //the entire GridView widget will be parsed via Pjax and rendered inside a yii\widgets\Pjax widget container
        'pjaxSettings'=>[
            'refreshGrid' => true,
            'neverTimeout'=>true,
            'options' => ['id' => '2'],
        ],
        'rowOptions' => function($dataProvider){
             if($dataProvider->operator_id == 0){
                return ['class' => 'success'];
            }             
        },
  'options'=>['id'=>'dynagrid-2'] // a unique identifier is important

Sample of editable column

        'class' => 'kartik\grid\EditableColumn',
        'attribute'=>'company_id',         
        'vAlign'=>'middle',
        'width'=>'250px',        
        'editableOptions'=> 
                [
                    'name' => 'company_id',                
                    'header' => 'Customer', 
                    'pjaxContainerId'=>'6',
                    'size' => 'sm',          
                    'format' => 'link',
                    'asPopover' => false,
                    'displayValueConfig' => $customerFilter,
                    'inputType' => 'dropDownList',                    
                    'data'=>$customerFilter, // any list of values
                    'options' => ['class'=>'form-control', 'prompt'=> 'Select Customer...'],                    
                ],                
        'value'=>function ($model){           
            if(isset($model->company_id) AND $model->company_id !=0){
                return Html::a($model->company_id, ['customers/view','id' => $model->company_id], [
                    'title'=>'View customer detail',                 
                ]);                 
            }else{
                return "(Not Set)";
            }
        },      
        'format'=>'raw',
        'filter'=>$customerFilter, 
        'noWrap'=>true

**Comment by ber5ien** [comment]
if i use popover then popover is displayed but then again if you press the button to apply the changes nothing happens

**Comment by kartik-v** [comment]
It will not work because the same HTML input identifier will be generated for the same attribute both the dynagrid and all jquery plugins (like EditableColumn) that rely on ID will fail.

You must set a different `options['id']` for each attribute inbut in editable widget options OR use a  different Model class extending from the same model so the auto gen iDs are different.

**Comment by racielbd** [comment]
Hi...
i'm having the same issue already use a dynamic options['id'] so it won't repeat but the editable only work at grid 1.. im using an expandable column for the grids

this is what I am trying to do

![imagen](https://user-images.githubusercontent.com/25595025/55642163-b8989480-579d-11e9-953d-7ab42b65cb45.png)

but in the second grid the editable does not come out...
this is the code of that column

```
[
  'class' => 'kartik\grid\EditableColumn',
   'attribute' => 'confCode',
   'vAlign' => 'middle',
   'headerOptions' => ['class' => 'kv-sticky-column'],
   'contentOptions' => ['class' => 'kv-sticky-column'],
   'editableOptions' => function ($model, $key, $index, $widget) {
       return [
             'header' => 'Confirm Code',
             'inputType' => kartik\editable\Editable::INPUT_TEXT,
             'options' => [
                 'id' => 'column-' . $model->idItinerary . '-' . $model->idProduct . '-' . $model->idParticipant,
              ]
        ];
    },
],
```

**Comment by enkr1** [comment]
For those who are still looking for an answer, this is how I fixed my issue: (I'm using tabsX in my case, so I pass the tabName to make the id unique)

```php

            [
                'class' => '\kartik\grid\EditableColumn',
                'attribute' => 'my_attribute',
                'editableOptions' => function ($model, $key, $index, $column) use ($tabName) {
                    return [
                        'inputType' => Editable::INPUT_TEXT,
                        'inputType' => kartik\editable\Editable::INPUT_TEXT,
                        'formOptions' => ['action' => ['...']],
                        'options' => [
                            'type' => 'number',
                            "id" => "$tabName-my_attribute-$index",
                        ],
                    ];
                },
            ],
            ```
