### ISSUE TITLE
EditableColumns not loading in the first time page is loaded but all works fine later

### ISSUE THREAD

**Issue by ber5ien** [kartik-v/yii2-dynagrid#97]
I am having the following issue. 

1. I load a page with my tickets.
2. There is a filter set up as me. this is stored in gird configuration store.
3. I press the cross to show all tickets not just me one.

![image](https://cloud.githubusercontent.com/assets/854403/11089941/e78dc5f4-8865-11e5-93f6-0ba40660a4f0.png)

The page is loading but the editable field are not being initialized and they cannot be clicked as per below example

![image](https://cloud.githubusercontent.com/assets/854403/11089905/a550e766-8865-11e5-80a0-aa82bad1a983.png)

If i press F5 to refresh the page all is working fine with no issue i can then reset the grid to get a view default to me and press x to remove me. It works perfectly fine later on.

I don't understand why I need to refresh the page when the page is being views first time to get this working.

Many Thanks for your help.

It looks like the filed are not loaded because there is filter set.

Example of editable columnt 
[
        'class' => 'kartik\grid\EditableColumn',
        'attribute'=>'company_id',         
        'vAlign'=>'middle',
        'width'=>'250px',   
        'editableOptions'=> function ($model) use ($customerFilter) {
            return [                
                'header'=>'Customer', 
                'size'=>'md',     
                'format' => 'link',
                'asPopover' => true,       
                'displayValueConfig' => $customerFilter,           
                'inputType' => Editable::INPUT_SELECT2,
                'options'=>[                    
                        'theme' => 'krajee',
                        'data' => $customerFilter,   
                        'pluginOptions'=>[
                               'allowClear' => true,
                        ],
                ],                                    
            ];
        },
        'value'=>function ($model){           
            if(isset($model->company_id) AND $model->company_id !=0){
                return Html::a($model->company_id, ['customers/view','id' => $model->company_id], [
                    'title'=>'View customer detail',                 
                ]);                 
            }else{
                return "(Not Set)";
            }
        },      
        'format'=>'raw',
        'filterType'=>GridView::FILTER_SELECT2,
        'filterWidgetOptions'=>[ 
                        'theme' => 'krajee',
                        'options' => ['placeholder' => 'Customer ...'],
                        'data' => $customerFilter,
                        'pluginOptions'=>[
                            'allowClear' => true,
                        ],
                    ],                
        'noWrap'=>true,
    ],

**Comment by ber5ien** [comment]
once f5 is press all is ok

![image](https://cloud.githubusercontent.com/assets/854403/11090045/92a14d9e-8866-11e5-850d-f715fb2e44b2.png)

I can reset the grid 

![image](https://cloud.githubusercontent.com/assets/854403/11090056/9d6a4532-8866-11e5-9a4e-c66931944ff7.png)

press the 'x' and all is good 

![image](https://cloud.githubusercontent.com/assets/854403/11090066/a9f13aa4-8866-11e5-8a40-9f7e362de2c0.png)

**Comment by ber5ien** [comment]
I have also another page without any default filter and it load fine first time without any issues.
So it looks like this is not working because the i have a filter setup.

Many Thanks

**Comment by kartik-v** [comment]
You may need to check if there are Javascript errors on your page (by looking at the browser console) or other JS conflicting with this.

**Comment by ber5ien** [comment]
Hi, 
Many thanks for tips.
Indeed there are some errors

![image](https://cloud.githubusercontent.com/assets/854403/11958886/650a13b2-a8c2-11e5-918e-e4e7ca4df09e.png)

then got the following once clicked on VM217:11

jQuery("#tickets-0-operator_id-cont").editable(editable_0b8d9295);

Would you be able to give me any advise on this ? 

Many thanks
Raf

**Comment by kartik-v** [comment]
Your resizable columns plugin is throwing error... you may try to disable resizable columns OR check why that is causing an error.

**Comment by ber5ien** [comment]
I have tried without it and it would make any difference.
I noticed that 4 asset are not loading by comparison both pages.

Perhaps this is because the the page first is loaded without any data and then search is triggered using ajax so the assets are not loaded because of that.  

It would look like during the ajax request there is not check if the editable columnt exist and asset are not loaded.

Is it possible force loading these assets even if on the page there is no editable column available?

kartik\editable\EditableAsset
sourcePath	/var/www/tickets/vendor/kartik-v/yii2-editable/assets
basePath	/var/www/tickets/web/assets/f78a12ea
baseUrl	/assets/f78a12ea
css	
css/editable.css
js	
js/editable.js
depends	
yii\web\JqueryAsset
yii\web\YiiAsset
yii\bootstrap\BootstrapAsset
kartik\editable\EditablePjaxAsset
sourcePath	/var/www/tickets/vendor/kartik-v/yii2-editable/assets
basePath	/var/www/tickets/web/assets/f78a12ea
baseUrl	/assets/f78a12ea
js	
js/editable-pjax.js
depends	
yii\web\JqueryAsset
yii\web\YiiAsset
yii\bootstrap\BootstrapAsset

**Comment by ber5ien** [comment]
Hi Kartik, 

I manage fix my issue by adding the following:

use kartik\editable\EditableAsset;
EditableAsset::register($this);

use kartik\editable\EditablePjaxAsset;
EditablePjaxAsset::register($this);

use kartik\popover\PopoverXAsset;
PopoverXAsset::register($this);

So it looks like if you open a page with search and then using ajax to load the data the plugins are not initialited becuase during the ajax request it's not check if the editable column exist

Many Thanks for your support!

**Comment by cognitivaxx** [comment]
I've tried this... no way, man. There will be another issues to attend to fix it?

**Comment by chodges** [comment]
First off Kartik I just want to say that your controls are **indispensable** and I really really appreciate your work.  

I'm also having a bunch of problems with this too.  i'm noticing that if I have only one editable column then the value NEVER gets sent to the control when I press the Pop-Ups submit button.   The 2nd editable column does send the value. 

BUT what I've also found is that if I use a the INPUT_SPIN it is not populating the spinner with my min/max range.  

So there seems to be a lot of issues with this control.

		[
			'class' => 'kartik\grid\EditableColumn',
			'attribute'=>'discount',
			'header'=>'Discount',
			'editableOptions'=>[
		        'header'=>'Discount',
		        'inputType'=>\kartik\editable\Editable::INPUT_SPIN,
		        'options'=>['pluginOptions'=>['min'=>0, 'max'=>5000]]
		    ],
		    'hAlign'=>'right',
		    'width'=>'100px',
		    'format'=>['decimal', 2],
		],
	
		[
			'class' => 'kartik\grid\EditableColumn',
			'attribute'=>'discount_override',
			'header'=>'Discount Override',
			'editableOptions'=>[
		        'header'=>'Discount Override',
		        'inputType'=>\kartik\editable\Editable::INPUT_SPIN,
		        'options'=>['pluginOptions'=>['min'=>0, 'max'=>5000]]
		    ],
		    'hAlign'=>'right',
		    'width'=>'100px',
		    'format'=>['decimal', 2],
		],

//And the Model:

		class OpportunityProduct extends \yii\db\ActiveRecord
		{
		    /**
		     * @inheritdoc
		     */
		    public static function tableName()
		    {
		        return 'opportunity_product';
		    }

		    /**
		     * @inheritdoc
		     */
		    public function rules()
		    {
		        return [
		            [['opportunity_id', 'product_id'], 'required'],
		            [['opportunity_id', 'product_id'], 'integer'],
		            [['base_fee'], 'number'],
					[['discount', 'discount_override'], 'number', 'min'=>0, 'max'=>100],
		            [['opportunity_id'], 'exist', 'skipOnError' => true, 'targetClass' => Opportunity::className(), 'targetAttribute' => ['opportunity_id' => 'opportunity_id']],
		            [['product_id'], 'exist', 'skipOnError' => true, 'targetClass' => Product::className(), 'targetAttribute' => ['product_id' => 'product_id']],
		        ];
		    }

When I try to edit the value look at my Spinner (First of all the pop-up is WAY too small.  It looks nothing like the layout of the pop-ups in Kartik's demo page.  But more importantly even though I'm specifying the min/max range **the values are not showing up in the spinner**:

<img width="329" alt="screen shot 2016-05-20 at 9 56 37 pm" src="https://cloud.githubusercontent.com/assets/197811/15446435/c1ac8468-1ed5-11e6-84a3-a7955bbed534.png">




**And here is one of the errors I'm seeing when I submit the change:**

<img width="979" alt="screen shot 2016-05-20 at 9 53 45 pm" src="https://cloud.githubusercontent.com/assets/197811/15446421/71df1130-1ed5-11e6-8e48-60a94a50c5c8.png">

So for right now the editable column is useless to me right now and I'm going to have to use another solution to make this work.  Any input you can provide Kartik would be soooo helpful.

Thank you.
