### ISSUE TITLE
Save filter - virtual attribute 

### ISSUE THREAD

**Issue by skophp** [kartik-v/yii2-dynagrid#98]
you can save a virtual attribute in a filter ? into database date column ( tbl_dynagrid_dtl ) contains [ ] if I try.
the data is displayed correctly and the filter input in the grid works .

**Comment by stivehu** [comment]
Hi!

I have same problem. Try your searchModel  object append this function:
`    
public function attributes()
    {
        return array_merge(parent::attributes(),['virtualAttr'] );
    }
`

or 
`
    public function attributes()
    {
        return array_merge(parent::attributes(), array_keys(get_object_vars($this)));
    }
`

**Comment by metola** [comment]
Hi @stivehu , I put second rewrite function (attributes) in my SearchModel, and this works fine.
Thanks.
