### ISSUE TITLE
IN Your demo apply stored filter and sort doesn't work

### ISSUE THREAD

**Issue by Enrica-r** [kartik-v/yii2-dynagrid#99]
Does you Dynagrid Demo work? Otherwise a too stupid to understand how to apply a stored filter.

1. I tried to filter something then I pushed to filter button and stored it by a name. Afterwards I filterd something else. Then I went back to the filter button and klicked on the stored name. It showed me the criteria in the modal box. After applying nothing happens. Is it my mistake or is the demo broken? I have same Issue on my own installation.

2. If you sort something in the demo it works and you get an order direction sign beside column label. If you sort another column the old sign doesn't disappear. If you store it you can see that it's multi sorted. How can you reset a multi sort? (potentially it's a question of documentation).

And also here, the stored sort can't be applied to the grid.

**Comment by kartik-v** [comment]
Yes the demo works without issues.

Multi column sorting needs to be set in your dataProvider sort... check yii docs.

**Comment by Enrica-r** [comment]
Thanks Kartik
Sorry for bothering you. Probably I'm too stupid. How can I apply the stored filter?
What I do is:
1. I filter something (eg. "Uly")
2. I open filter dialog and give a name "Uly" and I click the ok button.
3. I remove the current filter "Uly" and i get the whole list.
4. I open the filter dialog and click on the saved filter "Uly" and click on the ok button. I get the waiting dialog. Afterwards nothing happens. The whole unfiltered list is still there.

How can I apply stored filters? (same for sort).
Thanks

**Comment by kartik-v** [comment]
You need to set and apply saved filter and sort via the personalize button (colored wrench button). The personalize button applies saved columns, pagesize, filter, sort etc. all from one place.

**Comment by kartik-v** [comment]
To summarize,

The **Filter Button** and **Sort Button** in dynagrid is to be used to generate and save pre-configured filters and sorts (not to apply these).

To personalize and APPLY a saved filter or saved sort by default use the **Personalize Button** and select your filter or sort. The personalize button can be used for the following

- Set a default page size (no. of rows per page)
- Set a grid theme
- Choose a default saved filter
- Choose a default saved sort
- Reorder and Hide/Show Columns

**Comment by akorinek** [comment]
I've got the same problem with the demo page:

This is how to reproduce this problem:

1. Select Author "Aldous Huxley" as a filter.
2. Save custom filter as "huxley" using the filter button.
3. Deselect "Aldous Huxley" from the header filter dropdown
4. Click on wrench and select 'huxley' as the default filter.

Result: Table is not filtered. Expected to see only "Aldous Huxley" as author
